# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# From https://www.jamesward.com/2014/09/24/jekyll-on-heroku
# Exclude config, build files from the site
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

# Site settings
title: integration.blogspot
email: solveapuzzledev@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  A series of articles & blogs on agile, integration and innovation. I've worked across multiple 
  countries, industries and technology stacks and think I've learnt a few things along the way.:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://neilpiper-blog.herokuapp.com" # the base hostname & protocol for your site
twitter_username: NeilTPiper 
github_username:  n_piper 

# Build settings
markdown: kramdown
